# Generated by Django 3.1.5 on 2021-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='CPU',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='CPU_max_frequency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='RAM',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='audio_formats',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='availiable_memory',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='bluetooth_profiles',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brightness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cam_2nd_module_aperture',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cam_2nd_module_resolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cam_3rd_module_aperture',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cam_3rd_module_resolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cam_4th_module_aperture',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cam_4th_module_resolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cartridge_max_capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='cartridge_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contrast',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='digital_zoom_photo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='digital_zoom_video',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='front_video_resolution',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='max_time_4G',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='max_time_4G_talk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='max_time_music',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='max_time_video',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='max_time_wifi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='n_cores',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='optical_zoom_photo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='optical_zoom_video',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='pixel_density',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='sim_work_mode',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_formats',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_frame_rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='video_resolution',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
