# Generated by Django 3.1.5 on 2021-01-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210106_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='wifi',
            field=models.CharField(max_length=50),
        ),
    ]
