# Generated by Django 3.1.5 on 2021-01-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=25, unique=True, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тематика Статьи',
                'verbose_name_plural': 'Тематика Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleToScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.article')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.scope')),
            ],
            options={
                'ordering': ['-primary', 'scope__scope'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.ArticleToScope', to='articles.Scope'),
        ),
    ]
