# Generated by Django 3.1.5 on 2021-01-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletoscope',
            options={'ordering': ['-primary', 'scope__scope'], 'verbose_name': 'Тематика Статьи', 'verbose_name_plural': 'Тематики Статьи'},
        ),
    ]
