# Generated by Django 3.1.5 on 2021-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210108_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='scope',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название'),
        ),
    ]
