# Generated by Django 3.1.5 on 2021-01-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210108_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletoscope',
            options={'ordering': ['-is_main', 'scope__topic'], 'verbose_name': 'Тематика Статьи', 'verbose_name_plural': 'Тематики Статьи'},
        ),
        migrations.RenameField(
            model_name='articletoscope',
            old_name='primary',
            new_name='is_main',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='topic',
        ),
    ]
