# Generated by Django 3.1.5 on 2021-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210108_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='topic',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
    ]
