# Generated by Django 3.1.5 on 2021-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210108_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='topic',
            field=models.TextField(max_length=25, unique=True, verbose_name='Название'),
        ),
    ]
